### ISSUE TITLE
appVersion defaults to chartVersion, it shouldn't

### ISSUE THREAD

**Issue by yelhouti** [variantdev/chartify#4]
Hi,

Your library is used by helmfile, in the following code:
https://github.com/variantdev/chartify/blob/7c61f46c183ff9c83e1fd4164ea4317ab8089502/chartify.go#L214-L215
The appVersion is defaulted to the same value as the chartVersion.
This is often not the case, and it's better not to add it to Chart.yaml if not set.

Thanks in advance

**Comment by mumoshu** [comment]
@yelhouti Ah that's good point! Probably I didn't know that the appVersion was optional when I wrote the initial version of chartify. I'll try to fix it

**Comment by mumoshu** [comment]
https://github.com/variantdev/chartify/commit/8ff30374cb2a65af5167f3d47df81fe45d37b01d#diff-1c094adc4e7175fd1ea951f9fcb450a85b1dd5a86b4090ae3512364018f81464R275 fixes the issue in chartify (I unexpected mixed the another change into the same commit but anyway...

**Comment by mumoshu** [comment]
The above change is included in Helmfile since https://github.com/roboll/helmfile/pull/1803. Closing as resolved!
